name: Build & Push to Amazon ECR

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Build and push Docker image to ECR
      uses: docker/build-push-action@v6
      env:
        IMAGE_TAG_SHA: ${{ github.sha }}
        IMAGE_TAG_LATEST: latest
      with:
        context: ./application
        push: true
        tags: |
          255945442255.dkr.ecr.us-east-1.amazonaws.com/norman-3.4-repo:${{ env.IMAGE_TAG_LATEST }}
          255945442255.dkr.ecr.us-east-1.amazonaws.com/norman-3.4-repo:${{ env.IMAGE_TAG_SHA }}
    
    - name: Set image tag output
      id: vars
      run: echo "image_tag=${GITHUB_SHA}" >> $GITHUB_OUTPUT
    
    - name: Terraform Init & Apply
      working-directory: ./terraform
      run: |
        terraform init
        terraform apply -auto-approve \
          -var="image_tag=${{ steps.vars.outputs.image_tag }}" \
          -var="ecr_repository_url=255945442255.dkr.ecr.us-east-1.amazonaws.com/norman-3.4-repo"
